name = "rutasport"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/CalzadoAndres/browser"

[[d1_databases]]
binding = "DB"
database_name = "rutasport"
database_id = "51dfde01-249b-4320-8056-8179ea69f025"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "rutasport"
